simplesocial/groups/urls.py
from django.urls import path
from groups.views import CreateGroup, SingleGroup, ListGroup, JoinGroup, LeaveGroup

app_name = 'groups'

urlpatterns = [
    path('', ListGroup.as_view(), name='all'),
    path('new/', CreateGroup.as_view(), name='create'),
    path('posts/in/<slug>/', SingleGroup.as_view(), name='single'),
    path('join/<slug>/', JoinGroup.as_view(), name='join'),
    path('leave/<slug>', LeaveGroup.as_view(), name='leave'),
]

simplesocial/posts/urls.py
from django.urls import path
from posts.views import CreatePost, DeletePost, PostDetail, UserPost, PostList

app_name = 'posts'

urlpatterns = [
    path('', PostList.as_view(), name='all'),
    path('new/', CreatePost.as_view(), name='create'),
    path('by/<username>/', UserPost.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from simplesocial.views import HomePageView, TestPage, ThanksPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('test/', TestPage.as_view(), name='test'),
    path('thanks/', ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # allow us to connect to everything that django has everything under the hood for authorization
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),

]

simplesocial/groups/models.py
from django.db import models
from django.urls import reverse
# get the current user
from django.contrib.auth import get_user_model

# allows us to remove any characters that are not alpha-numeric, '_' or '-' ,
# it is used if we want to use a string that has spaces in it to be used as a part of url,
# slugify will lower case it and convert spaces into dashes so that it can be used as an url
from django.utils.text import slugify

# use markdown text (link embedding) into description
import misaka

# get info from the current user session
User = get_user_model()

# this is how we can use custom template tags
from django import template
register = template.Library()


# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})


    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


    class Meta:
        unique_together = ('group', 'user')

simplesocial/groups/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic
from groups.models import Group, GroupMember
from django.db import IntegrityError
from django.contrib import messages


# Create your views here.
class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DetailView):
    model = Group


class ListGroup(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        # if the user has already joined the group then it will show integrity error/
        # you can also skip this, then the except will then catch any error that will occur
        except IntegrityError:
            messages.warning(self.request, ("Warning you're already member of {}".format(group.name)))
        else:
            messages.success(self.request, ("You're are now a member of {} group".format(group.name)))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            # we are trying to get the group that the user wish to leave
            membership = GroupMember.objects.filter(user=self.request.user, group__slug=self.kwargs.get("slug")).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, "You can't leave this group because you aren't in it.")
        else:
            membership.delete()
            messages.success(
                self.request, "You have successfully left this group.")
        return super().get(request, *args, **kwargs)

simplesocial/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row">
  {% block pregroup %}{% endblock %}
  {% block group_content %}{% endblock %}
  {% block postgroup %}{% endblock %}
</div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="container">
  <h1>{{group.name}}</h1>
    <h3>{{ group.description_html | safe }}</h3>
    <br>
  <h4> Member Count: {{group.members.count}}</h4>

  <div class="content">
  	{% if user in group.members.all %}
  		<a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-times-circle-o"></span> Leave</a>
  	{% else %}
  		<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-check-circle-o"></span> Join</a>
  	{% endif %}

  </div>
</div>
{% endblock %}

{% block group_content %}

<div class="col-md-8">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<div class="container">
  <h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-primary btn-large">Create</button>
  	{% endbuttons %}
  </form>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<p>Welcome to the Groups Page! <br>Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		<a href="{% url 'groups:single' slug=group.slug %}"
		class="list-group-item list-group-item-action flex-column align-items-start">
			<h3 class="mb-1">{{ group.name }}</h3>
			<p class="mb-1">{{ group.description_html|safe }}</p>
			<div class="d-flex w-40 justify-content-between">
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}</small>
			<span></span><span></span>
			</div>
		</a>

		{% endfor %}
	</div>
</div>
{% endblock %}